### PR TITLE
Fix web scrapping and API V2 requests; add direct tracks streaming

### PR DESCRIPTION
**Pull request by dotandl**
I have corrected web scrapping again - I noticed that always the last element in the `data` array contains information about track/playlist/user.  
I changed every occurrence of `data[7]`, `data[6]`, `data[5]` and so on to `data[data.length - 1]`.

In [readme.md](https://github.com/Tenpi/soundcloud.ts/blob/master/readme.md) was written:
```md
Note that for playlists, `getV2` returns a 500 error so stick with `getAlt` for now.
```
I fixed it by changing `/playlists/soundcloud:playlists:${playlistID}` to just `/playlists/${playlistID}` (I've also done it with tracks and users).

Last change I've done is `streamTrackDirectly()` method in `Util` class. It returns `Readable` stream without downloading track before.

### CODE REVIEW

**Comment by Tenpi** [comment]
Thank you, your contributions are appreciated! The only thing is that you don't need to update the docs (they are going to link to your fork of the repo instead of this one), but I will fix it myself.

**Comment by Tenpi** [comment]
Also, there was a small bug here when waiting for the Promise to resolve. The resolve parameter to Promise is actually a function (and I also added the generic void type so typescript doesn't complain).
```ts
await new Promise<void>(resolve => stream.on("end", () => resolve()))
```

**Comment by dotandl** [comment]
The resolve parameter to `Promise` is a function and the second parameter to event handler (`on` method) is also a function (callback), so my code was correct (I've tested it and worked fine).  
This construction is very common, for example in [`sleep` function](https://stackoverflow.com/a/39914235/11730811):
```js
await new Promise(r => setTimeout(r, 2000));
```

Of course your code is fine too and thank you for adding generic `void` type to `Promise` (sometimes I forget that JavaScript is different from TypeScript and TS has generics).

**Comment by Tenpi** [comment]
So, the bug with your version is that the function is supposed to return a string (the download location), but you are returning the resolve parameter instead.

```ts
/*When the stream ends, return r*/
await new Promise(r => stream.on('end', () => r))

/*This is never executed, bug!*/
return finalMP3
```

Notice that for setTimeout, it's `setTimeout(r, 2000)` and not `setTimeout(() => r, 2000)`. What you have in the latter is a function that returns a function. I know that can be tricky to understand at first, but I hope it helps!

**Pull request merged**
